
export const Categories = [
  { id: 1, name: 'Top Up', icon: 'Zap' },
  { id: 2, name: 'Skincare', icon: 'Sparkles' },
  { id: 3, name: 'Fashion', icon: 'Shirt' },
  { id: 4, name: 'Elektronik', icon: 'Smartphone' },
  { id: 5, name: 'Hobi', icon: 'Gamepad2' },
  { id: 6, name: 'Voucher', icon: 'Ticket' },
  { id: 7, name: 'E-Wallet', icon: 'Wallet' },
  { id: 8, name: 'Premium', icon: 'Crown' },
];

export const Products = [
  {
    id: 1,
    name: 'BIOAQUA Skincare 1 Set Lengkap 6pcs With Brightening Serum Wajah / Acne Essence / Day & Night Pelembab Wajah Cream Krim / Hydrating Toner Wajah / Facial Wash Sabun Cuci Muka Skincare Paket',
    price: 140000,
    originalPrice: 200000,
    rating: 4.9,
    reviews: '1.2rb',
    sold: 10500,
    category: 'Skincare',
    image: '/bioaqua24k.png',
    isFlashSale: true,
    discount: '30%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['Whitening Set 6Pcs', 'Anti-Acne Set 6Pcs'],
    description: `BIOAQUA Skincare Set Lengkap 6Pcs hadir sebagai solusi perawatan wajah harian dengan rangkaian produk yang saling melengkapi untuk membantu menjaga kelembapan, kebersihan, dan tampilan kulit agar terlihat lebih sehat dan terawat.`
  },
  {
    id: 2,
    name: 'Akrilik Sertifikat Funded - Custom Payout Certificate Premium',
    price: 269000,
    originalPrice: 350000,
    rating: 5.0,
    reviews: '84',
    sold: 84,
    category: 'Sertifikat Funded',
    image: '/akrilik1.png',
    isFlashSale: false,
    discount: '23%',
    stock: 'Tersedia',
    tag: 'Eksklusif',
    variants: ['20x10', '20x15'],
    description: `Akrilik Sertifikat Funded premium cocok untuk pajangan meja, hadiah trader, dokumentasi payout, dan koleksi pencapaian funded account.`
  },
  {
    id: 3,
    name: 'Wispie Money Magnet Fitted Shirt | Kemeja Kerja Wanita Press Body Pinstripe Salur Pink',
    price: 132000,
    originalPrice: 176000,
    rating: 4.9,
    reviews: '4.7rb',
    sold: 10000,
    category: 'Fashion',
    image: '/wispie1.png',
    isFlashSale: true,
    discount: '25%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    description: `Kemeja wanita premium dengan desain fitted body yang memberikan tampilan lebih elegan, rapi, dan profesional.`
  },
  {
    id: 4,
    name: 'Rephatious T-shirt "Rpts412" Black Cotton Combed 24s',
    price: 76000,
    originalPrice: 95000,
    rating: 4.8,
    reviews: '124',
    sold: 450,
    category: 'Fashion',
    image: '/rephatious1.png',
    isFlashSale: true,
    discount: '20%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['M', 'L', 'XL'],
    description: `Kaos Rephatious Rpts412 berbahan Cotton Combed 24s yang nyaman, adem, and cocok digunakan sehari-hari.`
  },
  // Produk Premium Baru
  {
    id: 101,
    name: 'Canva Pro - Akun Premium Aktif 1 Bulan Full Garansi',
    price: 12000,
    rating: 4.9,
    reviews: '2.1rb',
    sold: 3500,
    category: 'Premium',
    image: 'https://picsum.photos/seed/canva/400/400',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Nikmati fitur premium Canva Pro untuk desain profesional tanpa batas.',
    type: 'digital'
  },
  {
    id: 102,
    name: 'YouTube Premium 1 Bulan - No Ads & Background Play',
    price: 27999,
    rating: 5.0,
    reviews: '5.4rb',
    sold: 8900,
    category: 'Premium',
    image: 'https://picsum.photos/seed/youtube/400/400',
    stock: 'Tersedia',
    tag: 'Terlaris',
    description: 'Nonton YouTube tanpa iklan dan bisa putar di latar belakang.',
    type: 'digital'
  },
  {
    id: 103,
    name: 'Viu Premium 1 Bulan - Akses Semua Drama Korea & Film',
    price: 10000,
    rating: 4.8,
    reviews: '900',
    sold: 1200,
    category: 'Premium',
    image: 'https://picsum.photos/seed/viu/400/400',
    stock: 'Tersedia',
    description: 'Akses tanpa batas ke drama Korea terbaru dan film Asia lainnya.',
    type: 'digital'
  },
  {
    id: 104,
    name: 'ChatGPT Plus Premium Account - Akses GPT-4 Turbo',
    price: 30000,
    rating: 4.9,
    reviews: '450',
    sold: 600,
    category: 'Premium',
    image: 'https://picsum.photos/seed/chatgpt/400/400',
    stock: 'Stok Habis',
    description: 'Akses kecerdasan buatan tercanggih GPT-4 dengan kecepatan tinggi.',
    type: 'digital'
  },
  {
    id: 105,
    name: 'CapCut Pro Premium - Unlock All Effects & Features',
    price: 10000,
    rating: 4.7,
    reviews: '320',
    sold: 450,
    category: 'Premium',
    image: 'https://picsum.photos/seed/capcut/400/400',
    stock: 'Stok Habis',
    description: 'Edit video tanpa batas dengan fitur pro CapCut.',
    type: 'digital'
  },
  {
    id: 106,
    name: 'Netflix Premium UHD 4K - Akun Sharing Private',
    price: 15000,
    rating: 4.9,
    reviews: '8.2rb',
    sold: 12000,
    category: 'Premium',
    image: 'https://picsum.photos/seed/netflix/400/400',
    stock: 'Stok Habis',
    description: 'Nonton film dan serial TV kualitas 4K UHD.',
    type: 'digital'
  },
  {
    id: 107,
    name: 'Spotify Premium 1 Bulan - Akun Individual / Family',
    price: 25000,
    rating: 4.9,
    reviews: '3.1rb',
    sold: 5000,
    category: 'Premium',
    image: 'https://picsum.photos/seed/spotify/400/400',
    stock: 'Stok Habis',
    description: 'Dengarkan musik tanpa iklan dengan kualitas suara terbaik.',
    type: 'digital'
  }
];

export const Banners = [
  {
    id: 1,
    title: 'Semua Kebutuhan Digital Dalam Satu Tempat',
    subtitle: 'Pulsa, Paket Data, Token PLN, E-Wallet, Top Up Game, BPJS dan Tagihan Internet',
    badges: ['Proses Instan', 'Aman & Terpercaya', '24 Jam Nonstop'],
    type: 'digital',
    gradient: 'from-blue-600 via-indigo-600 to-purple-700'
  },
  {
    id: 2,
    title: 'Belanja Lebih Hemat Setiap Hari',
    subtitle: 'Gratis ongkir, promo spesial, produk pilihan dan pengiriman cepat',
    badges: ['Gratis Ongkir', 'Promo Spesial', 'Produk Pilihan'],
    type: 'physical',
    gradient: 'from-emerald-500 via-teal-600 to-blue-600'
  }
];
