export const Categories = [
  { id: 1, name: 'Top Up', icon: 'Zap' },
  { id: 2, name: 'Beauty', icon: 'Droplet' },
  { id: 3, name: 'Fashion', icon: 'Shirt' },
  { id: 4, name: 'Elektronik', icon: 'Smartphone' },
  { id: 9, name: 'Aksesoris hp', icon: 'Smartphone' },
  { id: 5, name: 'Game', icon: 'Gamepad2' },
  { id: 6, name: 'Voucher', icon: 'Ticket' },
  { id: 7, name: 'E-Wallet', icon: 'Wallet' },
  { id: 8, name: 'Premium', icon: 'Crown' },
];

export const Vouchers = [
  {
    id: 101,
    title: 'GRATIS ONGKIR MARPAY',
    description: 'Nikmati gratis ongkir untuk pembelian produk fisik di MarPay.',
    benefit: 'Potongan Rp15rb',
    minSpend: 'Min. blj Rp50rb',
    expiry: '30 Jun 2026',
    expiryDate: '2026-06-30',
    code: 'ONGKIRMARPAY',
    type: 'shipping',
    icon: 'Truck',
    active: true,
    info: 'Min. blj Rp50.000',
    badge: '🚚 Gratis Ongkir',
    color: 'text-primary',
    bgColor: 'bg-primary/5',
    borderColor: 'border-primary/10'
  },
  {
    id: 102,
    title: 'NEW USER SPECIAL',
    description: 'Diskon 10% untuk seluruh pengguna baru MarPay.',
    benefit: 'Diskon 10%',
    minSpend: 'Tanpa Min. Belanja',
    expiry: '31 Des 2026',
    expiryDate: '2026-12-31',
    code: 'MARPAYBARU',
    type: 'discount',
    icon: 'Ticket',
    active: true,
    info: 'Berlaku 1x',
    badge: '🎟️ New User',
    color: 'text-orange-500',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-100'
  }
];

export const Products = [
  {
    id: 226,
    name: 'Screamous Kaos T-Shirt BOXY FIT 16s MAZAL',
    price: 108000,
    rating: 4.9,
    reviews: 420,
    sold: 1200,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/3mMVXq3M/IMG-1491.jpg',
    isFlashSale: false,
    discount: null,
    stock: 'Tersedia',
    tag: 'Produk Baru',
    gender: 'unisex',
    brand: 'Screamous',
    variants: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', imageUrl: 'https://i.ibb.co/3mMVXq3M/IMG-1491.jpg' },
      { name: 'White', imageUrl: 'https://i.ibb.co/5Xh1sbhf/IMG-1492.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['kaos', 'screamous', 'boxy fit', 'tshirt', 'unisex', 'fashion'],
    description: `SCREAMOUS T-SHIRT BOXY FIT MAZAL

Kaos dengan potongan Boxy Fit yang sedang tren, memberikan siluet kotak yang stylish. Menggunakan material Cotton Combed 16s yang lebih tebal dan kokoh namun tetap adem.

Detail Produk:
- Material: Cotton Combed 16s (Heavy Weight)
- Fit: Boxy Fit
- Detail: Screenprinted Graphics
- Pilihan Warna: Black & White

Panduan Ukuran (Boxy Fit):
S: Lebar 54cm | Panjang 66cm
M: Lebar 56cm | Panjang 68cm
L: Lebar 58cm | Panjang 70cm
XL: Lebar 60cm | Panjang 72cm
XXL: Lebar 62cm | Panjang 74cm`,
  },
  {
    id: 225,
    name: 'AccentAmbios Boxy Oversized T-Shirt Believe Black Unisex - Cotton Combed 20s',
    price: 88000,
    rating: 4.8,
    reviews: 156,
    sold: 540,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/351j6Q35/IMG-1490.jpg',
    isFlashSale: true,
    discount: '10%',
    stock: 'Tersedia',
    tag: 'Trending',
    gender: 'unisex',
    brand: 'AccentAmbios',
    variants: ['S', 'M', 'L', 'XL'],
    colors: [],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['kaos', 'oversized', 'boxy', 'accentambios', 'hitam', 'streetwear'],
    description: `ACCENTAMBIOS BELIEVE BLACK - BOXY OVERSIZED T-SHIRT

Tampil percaya diri dengan koleksi 'Believe' dari AccentAmbios. Menggunakan bahan Katun Combed 20s premium yang memiliki ketebalan pas untuk gaya oversized.

Spesifikasi:
- Bahan: Cotton Combed 20s
- Warna: Deep Black
- Cutting: Boxy Oversized
- Tekstur bahan lembut, menyerap keringat, dan tidak menerawang.

Cocok dipadukan dengan celana cargo atau baggy pants untuk look minimalis modern.`,
  },
  {
    id: 224,
    name: 'AccentAmbios Kaos Boxy Oversized Savage Abu Tua - Katun Combed 20s',
    price: 93000,
    rating: 5.0,
    reviews: 88,
    sold: 320,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/XkXmhtF9/IMG-1488.jpg',
    isFlashSale: false,
    discount: null,
    stock: 'Tersedia',
    tag: 'Produk Pilihan',
    gender: 'unisex',
    brand: 'AccentAmbios',
    variants: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Abu Tua', imageUrl: 'https://i.ibb.co/XkXmhtF9/IMG-1488.jpg' },
      { name: 'Detail Belakang', imageUrl: 'https://i.ibb.co/20LwwPYK/IMG-1489.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['kaos', 'boxy', 'oversized', 'abu tua', 'fashion pria', 'unisex', 'katun'],
    description: `ACCENTAMBIOS SAVAGE DARK GREY - BOXY OVERSIZED T-SHIRT

Kaos dengan material Cotton Combed 20s berkualitas tinggi. Potongan boxy memberikan kenyamanan ekstra dan kesan urban yang kuat.

Fitur Utama:
- Bahan High Quality Cotton Combed 20s.
- Warna: Dark Grey (Abu Tua).
- Model: Boxy Oversized (Lengan lebar dan badan rileks).
- Jahitan rapi standar distro premium.

Sangat nyaman untuk penggunaan harian maupun hangout.`,
  },
  {
    id: 223,
    name: 'SCARLETT (BEST SELLER!) - Extrait De Parfum 30ml - Unisex - Parfum Wanita',
    price: 59000,
    rating: 5.0,
    reviews: 12500,
    sold: 45000,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/DPB2RN0T/IMG-1486.jpg',
    isFlashSale: true,
    discount: '15%',
    stock: 'Tersedia',
    tag: 'Best Seller',
    gender: 'unisex',
    brand: 'Scarlett',
    variants: ['30ml'],
    colors: [
      { name: 'Velvet Rouge', imageUrl: 'https://i.ibb.co/DPB2RN0T/IMG-1486.jpg' },
      { name: 'Garden Of Whisper', imageUrl: 'https://i.ibb.co/VWm5RM0p/IMG-1487.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['parfum', 'scarlett', 'extrait de parfum', 'unisex', 'velvet rouge', 'garden of whisper'],
    description: `SCARLETT Extrait De Parfum 30ml. Parfum dengan konsentrasi tinggi yang dirancang untuk memberikan keharuman yang tahan lama hingga 10-12 jam.

Tersedia varian:
1. Velvet Rouge: Memberikan kesan mewah, elegan, dan berani dengan sentuhan floral and spicy.
2. Garden Of Whisper: Memberikan kesan menenangkan, segar, dan feminin seperti berada di taman bunga.

Cara Pakai: Semprotkan pada titik nadi seperti pergelangan tangan, leher, dan belakang telinga untuk hasil maksimal.`,
  },
  {
    id: 222,
    name: 'PINKBERRY Eau de Parfum Twinkle 50ml - Parfum wanita',
    price: 53000,
    rating: 4.9,
    reviews: 4200,
    sold: 12000,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/jZGb49pk/IMG-1485.jpg',
    isFlashSale: false,
    discount: null,
    stock: 'Tersedia',
    tag: 'Recommended',
    gender: 'female',
    brand: 'Pinkberry',
    variants: ['50ml'],
    colors: [],
    isFreeShipping: true,
    shippingFee: 0,
    tags: ['parfum', 'pinkberry', 'twinkle', 'wanita', 'edp', 'floral'],
    description: `Pinkberry Eau de Parfum Twinkle 50ml. Aroma yang memikat dengan perpaduan floral dan fruity yang memberikan kesan ceria dan feminin. Cocok untuk wanita yang aktif dan ingin tampil segar sepanjang hari.

Top Notes: Citrus, Berries
Middle Notes: Jasmine, Rose
Base Notes: Musk, Vanilla

Keunggulan:
- Aroma tahan lama 6-8 jam.
- Botol spray yang praktis dibawa bepergian.
- Terdaftar BPOM & Halal.`,
  },
  {
    id: 221,
    name: '(NEW LAUNCHING) Crusita - Superstar Extrait De Parfum 50ML',
    price: 185000,
    rating: 5.0,
    reviews: 840,
    sold: 2100,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/CsSTq079/IMG-1483.jpg',
    isFlashSale: false,
    discount: '5%',
    stock: 'Tersedia',
    tag: 'Produk Baru',
    gender: 'unisex',
    brand: 'Crusita',
    variants: ['50ml'],
    colors: [],
    isFreeShipping: true,
    shippingFee: 0,
    tags: ['parfum', 'crusita', 'superstar', 'unisex', 'extrait de parfum', 'new launching'],
    description: `(NEW LAUNCHING) Crusita - Superstar Extrait De Parfum 50ML. Simbol kepercayaan diri dan kemewahan dalam satu botol. Superstar dirancang untuk kamu yang ingin menjadi pusat perhatian dengan aroma yang bold dan memikat.

Karakter: Bold, Elegant, & Charismatic.
Longevity: Up to 12-15 hours on skin.
Sillage: Strong.

Dapatkan sensasi aroma kelas dunia dengan konsentrasi Extrait de Parfum tertinggi di kelasnya.`,
  },
  {
    id: 220,
    name: 'Mykonos - Satin Blanc Extrait de Parfum 100ml (Pre Order)',
    price: 289201,
    rating: 4.9,
    reviews: 3500,
    sold: 8000,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/zh4TjQSL/IMG-1482.jpg',
    isFlashSale: false,
    discount: null,
    stock: 'Tersedia',
    tag: 'Trending',
    gender: 'unisex',
    brand: 'Mykonos',
    variants: ['100ml'],
    colors: [],
    isFreeShipping: true,
    shippingFee: 0,
    tags: ['parfum', 'mykonos', 'satin blanc', 'unisex', 'extrait de parfum', 'viral'],
    description: `Mykonos Satin Blanc Extrait de Parfum 100ml. Rasakan kelembutan satin yang mewah dalam bentuk aroma. Satin Blanc adalah parfum yang menenangkan, bersih, dan sangat berkelas.

Aroma ini memadukan kesegaran floral putih dengan sentuhan milky yang lembut, menciptakan aura yang sopan namun tetap meninggalkan kesan mendalam bagi siapa pun yang menciumnya.

Top Notes: Bergamot, Apple
Middle Notes: Jasmine, White Floral
Base Notes: Sandalwood, Amber, Vanilla

Status: Pre-Order (Estimasi pengiriman sesuai antrean).`,
  },
  {
    id: 219,
    name: '[100% ORI] Glad2Glow [ 1PC Persediaan ] Moisturizer',
    price: 44890,
    rating: 4.9,
    reviews: 3200,
    sold: 8900,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/Q7mJpKBg/IMG-1455.jpg',
    isFlashSale: true,
    discount: '5%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Glad2Glow',
    variants: ['30g'],
    colors: [
      { name: 'Brightening 30g', imageUrl: 'https://i.ibb.co/Q7mJpKBg/IMG-1455.jpg' },
      { name: 'NEW PDRN-30g', imageUrl: 'https://i.ibb.co/35Z9bzk3/IMG-1454.jpg' },
      { name: 'Retinol 30g', imageUrl: 'https://i.ibb.co/fKnt0G8/IMG-1456.jpg' },
      { name: 'Blueberry 30g', imageUrl: 'https://i.ibb.co/4g2hgtwM/IMG-1457.jpg' },
      { name: 'Centelle 30g', imageUrl: 'https://i.ibb.co/d41YvqCj/IMG-1458.jpg' },
      { name: 'Dark Spot 30g', imageUrl: 'https://i.ibb.co/nNYw99dX/IMG-1459.jpg' },
      { name: 'Acne Moist 30g', imageUrl: 'https://i.ibb.co/dw3gtsRW/IMG-1460.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 6000,
    tags: ['moisturizer', 'glad2glow', 'skincare', 'brightening', 'retinol', 'acne'],
    description: `[100% ORIGINAL] Glad2Glow Moisturizer Series. Solusi hidrasi kulit wajah dengan berbagai varian yang disesuaikan dengan kebutuhan kulit Anda. Tersedia varian Brightening, PDRN, Retinol untuk anti-aging, Blueberry untuk skin barrier, Centella untuk menenangkan, Dark Spot, dan Acne Moist.`,
  },
  {
    id: 218,
    name: 'Brightening Serum Niacinamide collagen 20ml',
    price: 30200,
    rating: 4.8,
    reviews: 1540,
    sold: 4200,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/dJ3C8QXw/IMG-1461.jpg',
    isFlashSale: true,
    discount: null,
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Brand',
    variants: ['20ml'],
    colors: [],
    isFreeShipping: false,
    shippingFee: 7000,
    tags: ['serum', 'brightening', 'niacinamide', 'collagen', 'skincare'],
    description: `Brightening Serum dengan kandungan Niacinamide dan Collagen yang membantu mencerahkan kulit wajah, menyamarkan noda hitam, and menjaga elastisitas kulit agar tampak lebih kenyal and sehat.`,
  },
  {
    id: 217,
    name: 'Wardah Nature Daily Aloe Hydramild Essence Toner - 100ml',
    price: 23840,
    rating: 4.9,
    reviews: 2100,
    sold: 8500,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/cXcJB0q1/IMG-1452.jpg',
    isFlashSale: true,
    discount: null,
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Wardah',
    variants: ['100 ml'],
    colors: [],
    isFreeShipping: true,
    shippingFee: 0,
    tags: ['toner', 'wardah', 'aloe', 'hydramild', 'skincare', 'essence'],
    description: `Wardah Nature Daily Aloe Hydramild Essence Toner adalah perpaduan essence and toner dengan kandungan Aloe Vera yang menghidrasi kulit secara optimal. Tekstur ringan, cepat meresap, and memberikan efek menenangkan bagi kulit.`,
  },
  {
    id: 216,
    name: 'The Originote Toner | Untuk Mencerahkan & Melembapkan Wajah',
    price: 24520,
    rating: 4.8,
    reviews: 1420,
    sold: 6200,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/fGdgqtwt/IMG-1449.jpg',
    isFlashSale: true,
    discount: null,
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'The Originote',
    variants: ['Default'],
    colors: [
      { name: 'Toner H-llow', imageUrl: 'https://i.ibb.co/fGdgqtwt/IMG-1449.jpg' },
      { name: 'Toner Ceraluronic', imageUrl: 'https://i.ibb.co/fGdgqtwt/IMG-1449.jpg' }
    ],
    isFreeShipping: true,
    shippingFee: 0,
    tags: ['toner', 'the originote', 'skincare', 'mencerahkan', 'melembapkan'],
    description: `The Originote Toner dirancang khusus untuk mencerahkan and menjaga kelembapan kulit wajah. Formula efektif yang membantu menyeimbangkan pH kulit setelah mencuci muka and mempersiapkan kulit untuk tahap skincare selanjutnya.`,
  },
  {
    id: 215,
    name: 'SCORA Salicylic Acid Gentle Low pH Cleanser Sabun Cuci Muka Oily Acne Prone Skin Friendly',
    price: 35000,
    rating: 4.9,
    reviews: 1100,
    sold: 5200,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/QFjzwWfb/IMG-1448.jpg',
    isFlashSale: true,
    discount: '5%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Scora',
    variants: ['100 ml'],
    colors: [],
    isFreeShipping: false,
    shippingFee: 5000,
    tags: ['skincare', 'scora', 'cleanser', 'salicylic acid', 'oily skin', 'acne prone', 'sabun muka'],
    description: `SCORA Salicylic Acid Gentle Low pH Cleanser adalah pembersih wajah yang dirancang khusus untuk kulit berminyak and berjerawat (acne-prone). Mengandung Salicylic Acid yang efektif membersihkan pori-pori and mengurangi minyak berlebih tanpa merusak skin barrier.`,
  },
  {
    id: 214,
    name: 'Wardah Cica Aloe Low pH Hydramild Facial Wash Nature Daily Sabun Cuci Muka Membersihkan secara Lembut dan Menghidrasi Kulit - Skincare',
    price: 18223,
    rating: 4.9,
    reviews: 4200,
    sold: 10000,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/CpvcY4nk/IMG-1446.jpg',
    isFlashSale: true,
    discount: '15%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Wardah',
    variants: ['Default'],
    colors: [
      { name: '50 ml', imageUrl: 'https://i.ibb.co/CpvcY4nk/IMG-1446.jpg' },
      { name: '100 ml', imageUrl: 'https://i.ibb.co/DDZDRQCp/IMG-1447.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 7000,
    tags: ['skincare', 'wardah', 'facial wash', 'cica aloe', 'nature daily', 'sabun cuci muka', 'hidrasi'],
    description: `Wardah Cica Aloe Low pH Hydramild Facial Wash adalah sabun cuci muka dengan pH rendah yang membersihkan secara lembut tanpa membuat kulit kering. Mengandung Aloe Vera and Centella Asiatica (Cica) yang menghidrasi and menenangkan kulit. Cocok untuk semua jenis kulit, non-comedogenic, and non-acnegenic.`,
  },
  {
    id: 213,
    name: 'WARDAH UV Shield Acne Calming Sunscreen Moisturizer SPF 35 PA+++ | Jerawat dan Bekas',
    price: 30000,
    rating: 4.8,
    reviews: 850,
    sold: 2500,
    category: 'Beauty',
    imageUrl: 'https://i.ibb.co/N2pw9xdp/IMG-1445.jpg',
    isFlashSale: true,
    discount: '10%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Wardah',
    variants: ['Default'],
    colors: [],
    isFreeShipping: false,
    shippingFee: 6000,
    tags: ['skincare', 'wardah', 'sunscreen', 'acne calming', 'spf 35', 'perawatan wajah', 'jerawat'],
    description: `Wardah UV Shield Acne Calming Sunscreen Moisturizer SPF 35 PA+++ adalah sunscreen yang diformulasikan khusus untuk kulit berjerawat and bekas jerawat. Tekstur ringan, tidak lengket, and memberikan perlindungan optimal dari sinar UV sekaligus menenangkan jerawat.`,
  },
  {
    id: 212,
    name: 'Alpha Shirt - Kemeja Fitted Wanita | Fitted Shirt Garis Stripe Karet | Atasan Lengan Panjang Kantor',
    price: 72000,
    rating: 4.9,
    reviews: 1240,
    sold: 4500,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/6JfnkWcW/IMG-1437.jpg',
    isFlashSale: false,
    discount: '10%',
    stock: 'Tersedia',
    tag: 'Produk Baru',
    gender: 'female',
    brand: 'Brand',
    variants: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Burgundy', imageUrl: 'https://i.ibb.co/6JfnkWcW/IMG-1437.jpg' },
      { name: 'Abu Abu', imageUrl: 'https://i.ibb.co/6JfnkWcW/IMG-1437.jpg' },
      { name: 'Rose Cream', imageUrl: 'https://i.ibb.co/R4ZySWg1/IMG-1440.jpg' },
      { name: 'Hitam', imageUrl: 'https://i.ibb.co/jvnMf5Hv/IMG-1438.jpg' },
      { name: 'Mahogany', imageUrl: 'https://i.ibb.co/xtwV88mz/IMG-1441.jpg' },
      { name: 'Broken White', imageUrl: 'https://i.ibb.co/Y49xVXm5/IMG-1442.jpg' },
      { name: 'Navy', imageUrl: 'https://i.ibb.co/PZytJjLw/IMG-1443.jpg' },
      { name: 'Rose Pink', imageUrl: 'https://i.ibb.co/jk49jXGB/IMG-1444.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['fashion', 'kemeja', 'wanita', 'fitted shirt', 'kantor', 'formal', 'stripe', 'alpha shirt'],
    description: `Alpha Shirt adalah kemeja fitted wanita premium dengan motif garis (stripe) yang memberikan kesan ramping and elegan. Terbuat dari bahan berkualitas yang adem and nyaman digunakan sepanjang hari, cocok untuk aktivitas kantor maupun acara formal.`,
  },
  {
    id: 211,
    name: 'ESSI Elton Fitted Shirt - kemeja fitted / kemeja ketat wanita / kemeja kantor / atasan hijab',
    price: 160000,
    rating: 4.9,
    reviews: 842,
    sold: 1250,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg',
    isFlashSale: false,
    discount: '15%',
    stock: 'Tersedia',
    tag: 'Produk Baru',
    gender: 'female',
    brand: 'ESSI',
    variants: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' },
      { name: 'Grey', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' },
      { name: 'Coffe', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' },
      { name: 'White', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' },
      { name: 'Vanilla', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' },
      { name: 'Navy', imageUrl: 'https://i.ibb.co/wZ22cHFX/IMG-1435.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['fashion', 'kemeja', 'wanita', 'fitted shirt', 'kantor', 'formal', 'hijab style', 'essi'],
    description: `ESSI Elton Fitted Shirt adalah kemeja fitted premium dengan potongan ketat yang memberikan kesan elegan and profesional.`,
  },
  {
    id: 210,
    name: 'Oro Pants Wanita Celana Kekinian Kerja Kantor High Waist Korean Style Celana Anti Kusut Premium',
    price: 59000,
    rating: 4.8,
    reviews: 1200,
    sold: 3500,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg',
    isFlashSale: true,
    discount: '30%',
    stock: 'Tersedia',
    tag: 'Trending',
    gender: 'female',
    brand: 'Oro',
    variants: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Beige', imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg' },
      { name: 'Hitam', imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg' },
      { name: 'Abu Muda', imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg' },
      { name: 'Abu Tua', imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg' },
      { name: 'Mocca', imageUrl: 'https://i.ibb.co/8g5kRP5j/IMG-1434.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['fashion', 'celana', 'wanita', 'high waist', 'korean style', 'kantor', 'kerja', 'anti kusut'],
    description: `Oro Pants adalah celana high waist bergaya Korean Style yang dirancang khusus untuk kebutuhan kerja and kantor.`,
  },
  {
    id: 209,
    name: 'Wispie Girl Boss Shirt',
    price: 140900,
    rating: 4.9,
    reviews: 2400,
    sold: 10000,
    category: 'Fashion',
    imageUrl: 'https://i.ibb.co/pC2pp68/IMG-1164.jpg',
    isFlashSale: true,
    discount: '33%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    gender: 'female',
    brand: 'Wispie',
    variants: ['XS', 'M', 'XL'],
    colors: [
      { name: 'Pink', imageUrl: 'https://i.ibb.co/pC2pp68/IMG-1164.jpg' },
      { name: 'Biru', imageUrl: 'https://i.ibb.co/pC2pp68/IMG-1164.jpg' },
      { name: 'Hijau', imageUrl: 'https://i.ibb.co/pC2pp68/IMG-1164.jpg' }
    ],
    isFreeShipping: false,
    shippingFee: 8000,
    tags: ['fashion', 'kemeja', 'wanita', 'wispie', 'kerja', 'kantor', 'girl boss'],
    description: `Wispie Girl Boss Shirt merupakan kemeja premium dengan desain modern yang memberikan kesan profesional and elegan.`,
  },
  {
    id: 206,
    name: 'BETTERHALF Celana Pendek Pria Polos Short Pants Boardshort - Black',
    price: 47320,
    originalPrice: 86000,
    rating: 4.9,
    reviews: 6200,
    sold: 10000,
    category: 'Fashion',
    image: '/celana1.png',
    isFlashSale: true,
    discount: '45%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['M', 'L', 'XL'],
    shippingFee: 12000,
    isFreeShipping: false,
    description: `BETTERHALF Celana Pendek Cowo Polos Short Pants Boardshort - Black`,
  },
  {
    id: 205,
    name: 'Kemeja Wanita Salur Alba Top – Stripe Fitted Shirt Slim Fit Lengan Pendek Casual Kantor Korean Style',
    price: 59999,
    originalPrice: 89000,
    rating: 4.9,
    reviews: 630,
    sold: 8000,
    category: 'Fashion',
    image: '/fitted2.png',
    isFlashSale: true,
    discount: '33%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['S-M', 'L-XL'],
    colors: [
      { name: 'Hitam🔥', imageUrl: '/fitted2.png' },
      { name: 'Grey', imageUrl: '/fitted2.png' },
      { name: 'Putih', imageUrl: '/fitted2.png' },
      { name: 'Maroon', imageUrl: '/fitted2.png' },
      { name: 'Mahogany', imageUrl: '/fitted2.png' },
      { name: 'Navy', imageUrl: '/fitted2.png' }
    ],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Alba Top Kemeja Wanita Salur dengan desain Stripe Fitted Shirt Slim Fit.`,
  },
  {
    id: 201,
    name: 'Case iPhone Clear MagSafe Premium Anti Shock Transparan',
    price: 14899,
    originalPrice: 24999,
    rating: 4.9,
    reviews: 1200,
    sold: 10500,
    category: 'Aksesoris hp',
    image: '/case1.png',
    isFlashSale: true,
    discount: '40%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: [
      'iPhone 7/8', 'iPhone 7+/8+', 'iPhone X/XS', 'iPhone XR', 'iPhone 11', 'iPhone 11 Pro', 'iPhone 11 Pro Max', 'iPhone 12', 'iPhone 12 Pro', 'iPhone 12 Pro Max', 'iPhone 13', 'iPhone 13 Pro', 'iPhone 13 Pro Max',
      'iPhone 14', 'iPhone 14 Pro', 'iPhone 14 Pro Max', 'iPhone 15', 'iPhone 15 Plus', 'iPhone 15 Pro', 'iPhone 15 Pro Max', 'iPhone 16', 'iPhone 16 Plus', 'iPhone 16 Pro', 'iPhone 16 Pro Max', 'iPhone 17', 'iPhone 17 Air', 'iPhone 17 Pro', 'iPhone 17 Pro Max'
    ],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Case iPhone Clear MagSafe Premium dengan desain transparan elegan.`
  },
  {
    id: 202,
    name: 'Case iPhone Street Art Premium',
    price: 23999,
    originalPrice: 49999,
    rating: 4.9,
    reviews: 1500,
    sold: 10000,
    category: 'Aksesoris hp',
    image: '/case2.png',
    isFlashSale: true,
    discount: '52%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: [
      'iPhone 7/8', 'iPhone 7+/8+', 'iPhone X/XS', 'iPhone XR', 'iPhone XS Max',
      'iPhone 11', 'iPhone 11 Pro', 'iPhone 11 Pro Max',
      'iPhone 12', 'iPhone 12 Pro', 'iPhone 12 Pro Max',
      'iPhone 13', 'iPhone 13 Pro', 'iPhone 13 Pro Max',
      'iPhone 14', 'iPhone 14 Plus', 'iPhone 14 Pro', 'iPhone 14 Pro Max',
      'iPhone 15', 'iPhone 15 Plus', 'iPhone 15 Pro', 'iPhone 15 Pro Max'
    ],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Case iPhone Street Art Premium with desain grafiti modern.`
  },
  {
    id: 203,
    name: 'Everyday Pants - Stripe Pants - Celana Panjang Wanita Baggy Kantor Kuliah Motif Garis Kulot Pinstripe',
    price: 59252,
    originalPrice: 85000,
    rating: 4.8,
    reviews: 2700,
    sold: 10000,
    category: 'Fashion',
    image: '/baggy1.png',
    isFlashSale: true,
    discount: '30%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['Standar (BB 35-55Kg)', 'Jumbo (BB 56-70Kg)', 'Super Jumbo (BB 71-85Kg)'],
    colors: [
      { name: 'Abu Grey', imageUrl: '/baggy1.png' },
      { name: 'Hitam', imageUrl: '/baggy1.png' },
      { name: 'Putih', imageUrl: '/baggy1.png' },
      { name: 'Navi', imageUrl: '/baggy1.png' },
      { name: 'Mahogani', imageUrl: '/baggy1.png' },
      { name: 'Khaki', imageUrl: '/baggy1.png' },
      { name: 'Ice Blue', imageUrl: '/baggy1.png' }
    ],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Everyday Stripe Pants merupakan celana wanita model baggy kulot premium.`,
  },
  {
    id: 204,
    name: 'Kemeja Wanita Fitted Luna Stripe Atasan Salur Korean Style Terbaru',
    price: 59000,
    originalPrice: 89000,
    rating: 4.9,
    reviews: 154,
    sold: 1200,
    category: 'Fashion',
    image: '/fitted1.png',
    isFlashSale: true,
    discount: '34%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['M', 'L', 'XL'],
    colors: [
      { name: 'Choco Stripe', imageUrl: '/fitted1.png' }
    ],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Luna Stipe Kemeja Fitted bahan SemiWoll Stripe.`,
  },
  {
    id: 3,
    name: 'Wispie Money Magnet Fitted Shirt | Kemeja Kerja Wanita Press Body Pinstripe Salur Pink',
    price: 132000,
    originalPrice: 176000,
    rating: 4.9,
    reviews: 4700,
    sold: 10000,
    category: 'Fashion',
    image: '/wispie1.png',
    isFlashSale: true,
    discount: '25%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['S', 'M', 'L', 'XL', '2XL', '3XL'],
    shippingFee: 12000,
    isFreeShipping: false,
    description: `Kemeja wanita premium with desain fitted body.`
  },
  {
    id: 2,
    name: 'Akrilik Sertifikat Funded - Custom Payout Certificate Premium',
    price: 269000,
    originalPrice: 350000,
    rating: 5.0,
    reviews: 84,
    sold: 84,
    category: 'Sertifikat Funded',
    image: '/akrilik1.png',
    isFlashSale: false,
    discount: '23%',
    stock: 'Tersedia',
    tag: 'Best Seller',
    variants: ['20x10', '20x15'],
    shippingFee: 0,
    isFreeShipping: true,
    description: `Akrilik Sertifikat Funded premium cocok untuk trader.`,
  },
  {
    id: 6,
    name: 'BRTWL Hoodie Boxy | Hoodie Oversize Unisex Fleece Cotton - Mercy Series',
    price: 203230,
    originalPrice: 259000,
    rating: 4.8,
    reviews: 438,
    sold: 3200,
    category: 'Fashion',
    image: '/hoodie1.png',
    isFlashSale: true,
    discount: '22%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['M', 'L', 'XL'],
    shippingFee: 8000,
    isFreeShipping: false,
    description: `Hoodie boxy oversize unisex berbahan fleece cotton.`
  },
  {
    id: 1,
    name: 'BIOAQUA Skincare 1 Set Lengkap 6pcs With Brightening Serum Wajah',
    price: 140000,
    originalPrice: 200000,
    rating: 4.9,
    reviews: 1200,
    sold: 10500,
    category: 'Kecantikan',
    image: '/bioaqua24k.png',
    isFlashSale: true,
    discount: '30%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['Whitening Set 6Pcs', 'Anti-Acne Set 6Pcs'],
    shippingFee: 15000,
    isFreeShipping: false,
    description: `BIOAQUA Skincare Set Lengkap 6Pcs.`
  },
  {
    id: 207,
    name: 'Azarine Calm My Acne Sunscreen Moisturiser SPF35 PA+++ [LOLOS UJI INVIVO INVITRO] Chemical Sunscreen Gel Untuk Kulit Berminyak Berjerawat Sensitif 40ml',
    price: 47000,
    originalPrice: 59000,
    rating: 4.9,
    reviews: 7800,
    sold: 10000,
    category: 'Kecantikan',
    image: '/azarine1.png',
    isFlashSale: true,
    discount: '20%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    shippingFee: 0,
    isFreeShipping: true,
    description: 'Sunscreen gel (chemical sunscreen) yang ringan and dingin di kulit.',
  },
  {
    id: 208,
    name: 'Wardah UV Shield Acne Calming Sunscreen Serum SPF 50 PA++++',
    price: 28000,
    originalPrice: 49900,
    rating: 4.9,
    reviews: 10000,
    sold: 50000,
    category: 'Kecantikan',
    image: '/wardah1.png',
    isFlashSale: true,
    discount: '44%',
    stock: 'Tersedia',
    tag: 'Produk Viral',
    variants: ['Acne Calming SPF50 25ml', 'Acne Calming SPF35 35ml', 'Acne Calming SPF50 40ml'],
    shippingFee: 8000,
    isFreeShipping: false,
    description: `Wardah UV Shield Acne Calming Sunscreen Serum SPF 50 PA++++.`,
  },
  {
    id: 101,
    name: 'Canva Pro - Akun Premium Aktif 1 Bulan Full Garansi',
    price: 12000,
    rating: 4.9,
    reviews: 2100,
    sold: 3500,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Nikmati fitur premium Canva Pro.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 102,
    name: 'Spotify Premium - Akun Private / Family 1 Bulan Full Garansi',
    price: 15000,
    rating: 4.9,
    reviews: 4800,
    sold: 8200,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Musik tanpa iklan with Spotify Premium.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 103,
    name: 'YouTube Premium - Akun Private 1 Bulan Bebas Iklan',
    price: 10000,
    rating: 4.8,
    reviews: 3200,
    sold: 6500,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Nonton video tanpa gangguan iklan.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 104,
    name: 'Netflix Premium - Sharing / Private Profile 4K UHD 1 Bulan',
    price: 35000,
    rating: 4.7,
    reviews: 1900,
    sold: 4200,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Recommended',
    description: 'Streaming film and series kualitas 4K Ultra HD.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 105,
    name: 'CapCut Pro - Akun Premium Aktif 1 Bulan Full Fitur',
    price: 15000,
    rating: 4.9,
    reviews: 950,
    sold: 2100,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Akses semua fitur editing pro CapCut.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 106,
    name: 'ChatGPT Plus - Akses GPT-4 & DALL-E 3 Shared 1 Bulan',
    price: 45000,
    rating: 4.9,
    reviews: 150,
    sold: 500,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Hot Item',
    description: 'Gunakan kecerdasan AI terbaru GPT-4.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 107,
    name: 'Vidio Premier Platinum - Akun 1 Bulan Full Garansi',
    price: 15000,
    rating: 4.8,
    reviews: 420,
    sold: 1200,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Recommended',
    description: 'Nonton bola and konten eksklusif lainnya di Vidio.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  },
  {
    id: 108,
    name: 'Alight Motion Premium - Akun Full Fitur No Watermark 1 Bulan',
    price: 12000,
    rating: 4.9,
    reviews: 310,
    sold: 850,
    category: 'Premium',
    image: '/premium1.png',
    stock: 'Tersedia',
    tag: 'Best Seller',
    description: 'Edit motion graphic tanpa watermark.',
    type: 'digital',
    shippingFee: 0,
    isFreeShipping: true
  }
];

export const Banners = [
  {
    id: 1,
    title: 'Semua Kebutuhan Digital Dalam Satu Tempat',
    subtitle: 'Pulsa, Paket Data, Token PLN, E-Wallet, Top Up Game, BPJS and Tagihan Internet',
    badges: ['PROSES INSTAN', 'AMAN & TERPERCAYA', '24 JAM NONSTOP'],
    type: 'digital',
    gradient: 'from-blue-600 via-indigo-600 to-purple-700'
  },
  {
    id: 2,
    title: 'Belanja Lebih Hemat Setiap Hari',
    subtitle: 'Gratis ongkir, promo spesial, produk pilihan and pengiriman cepat',
    badges: ['GRATIS ONGKIR', 'PROMO SPESIAL', 'PRODUK PILIHAN'],
    type: 'physical',
    gradient: 'from-emerald-500 via-teal-600 to-blue-600'
  }
];
